# Generated by Django 5.2.4 on 2025-08-13 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
